In [14]:
import pandas as pd
import numpy as np

from math import radians, sin, cos, sqrt, atan2

In [15]:
# Station Metadata
station_df = pd.read_csv("../data/processed/feature_engineered_ev_dataset.csv")

# Demand Profile
demand_df = pd.read_csv("../data/processed/demand_profile.csv")

# Traffic Profile
traffic_profile = pd.read_csv("../data/processed/traffic_profile.csv")

# Area Coordinates
area_df = pd.read_csv("../data/external/area_coordinates.csv")

In [16]:
print(station_df.shape)
print(demand_df.shape)
print(traffic_profile.shape)
print(area_df.shape)

(2229, 61)
(4, 8)
(100, 7)
(25, 3)

In [17]:
station_df.head(2)
station_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2229 entries, 0 to 2228
Data columns (total 61 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   address                              2229 non-null   str
 1   latitude                             2229 non-null   float64
 2   longitude                            2229 non-null   float64
 3   staff                                2229 non-null   int64
 4   postal_code                          2229 non-null   int64
 5   available                            2229 non-null   float64
 6   capacity                             2229 non-null   float64
 7   cost_per_unit                        2229 non-null   float64
 8   total                                2229 non-null   float64
 9   supports_upi                         2229 non-null   int64
 10  supports_cash                        2229 non-null   int64
 11  supports_card                        2229 non-null   int64
 12  supports_wallet                      2229 non-null   int64
 13  payment_methods                      2229 non-null   int64
 14  is_24x7                              2229 non-null   int64
 15  open_hour                            2229 non-null   int64
 16  close_hour                           2229 non-null   int64
 17  supports_2W                          2229 non-null   int64
 18  supports_3W                          2229 non-null   int64
 19  supports_4W                          2229 non-null   int64
 20  power_type_AC                        2229 non-null   int64
 21  power_type_AC/DC                     2229 non-null   int64
 22  power_type_DC                        2229 non-null   int64
 23  zone_central delhi                   2229 non-null   int64
 24  zone_east delhi                      2229 non-null   int64
 25  zone_north delhi                     2229 non-null   int64
 26  zone_north east delhi                2229 non-null   int64
 27  zone_north west delhi                2229 non-null   int64
 28  zone_south delhi                     2229 non-null   int64
 29  zone_south east delhi                2229 non-null   int64
 30  zone_south west delhi                2229 non-null   int64
 31  zone_west delhi                      2229 non-null   int64
 32  charger_type_5A/15A Socket           2229 non-null   int64
 33  charger_type_AC001                   2229 non-null   int64
 34  charger_type_CCS/ CHAdeMO            2229 non-null   int64
 35  charger_type_CCS2                    2229 non-null   int64
 36  charger_type_CCS2/CHADEMO/TYPE 2 AC  2229 non-null   int64
 37  charger_type_CHAdeMO                 2229 non-null   int64
 38  charger_type_DC                      2229 non-null   int64
 39  charger_type_DC001                   2229 non-null   int64
 40  charger_type_Type 2                  2229 non-null   int64
 41  charger_type_battery_swapping        2229 non-null   int64
 42  vendor_name_BLUSMART                 2229 non-null   int64
 43  vendor_name_BSES                     2229 non-null   int64
 44  vendor_name_BluSmart                 2229 non-null   int64
 45  vendor_name_E-Fill Electric          2229 non-null   int64
 46  vendor_name_EEE                      2229 non-null   int64
 47  vendor_name_EESL                     2229 non-null   int64
 48  vendor_name_ElectriVa                2229 non-null   int64
 49  vendor_name_GensolCharge Pvt. Ltd.   2229 non-null   int64
 50  vendor_name_HPCL                     2229 non-null   int64
 51  vendor_name_JBM Renewables           2229 non-null   int64
 52  vendor_name_PlugNgo                  2229 non-null   int64
 53  vendor_name_Powerbank                2229 non-null   int64
 54  vendor_name_Pvt. Ltd.                2229 non-null   int64
 55  vendor_name_REIL                     2229 non-null   int64
 56  vendor_name_REVOS                    2229 non-null   int64
 57  vendor_name_Smart E                  2229 non-null   int64
 58  vendor_name_Sun Mobility             2229 non-null   int64
 59  vendor_name_TPDDL                    2229 non-null   int64
 60  vendor_name_Verdemobility            2229 non-null   int64
dtypes: float64(6), int64(54), str(1)
memory usage: 1.0 MB

In [18]:

traffic_profile.head(2)

,Area,time_of_day,trips,avg_density,density_norm,trips_norm,Traffic_Score
0,AIIMS,Afternoon,83,2.168675,0.458258,0.570093,0.491809
1,AIIMS,Evening Peak,120,2.983333,0.876401,0.915888,0.888247

In [19]:
area_df.head(2)

              Area  Latitude  Longitude
0      Vasant Kunj   28.5245    77.1540
1  Greater Kailash   28.5484    77.2387

In [20]:
station_df["Utilization_Score"] = (
    1 - (station_df["available"] / station_df["total"])
)
station_df["Utilization_Score"].value_counts()

Utilization_Score
0.000000    2112
1.000000      95
0.500000      21
0.333333       1
Name: count, dtype: int64

In [21]:
station_df["total"].value_counts().sort_index()

total
1.0     2059
2.0      121
3.0       29
4.0       10
6.0        2
7.0        2
12.0       3
13.0       1
20.0       1
40.0       1
Name: count, dtype: int64

In [22]:
station_df["available"].value_counts().sort_index()

available
0.0       95
1.0     2016
2.0       89
3.0       11
4.0       10
7.0        2
12.0       3
13.0       1
20.0       1
40.0       1
Name: count, dtype: int64

In [23]:
station_df["Capacity_Norm"] = (
    station_df["capacity"] - station_df["capacity"].min()
) / (
    station_df["capacity"].max() - station_df["capacity"].min()
)
station_df["Capacity_Norm"].value_counts()

Capacity_Norm
0.000000    1872
0.084355     151
1.000000      75
0.134823      37
0.026676      19
0.163663      16
0.047585      16
0.379957      16
0.178082       9
0.048306       8
0.192502       4
0.029560       2
0.120404       1
0.336698       1
0.091565       1
0.408796       1
Name: count, dtype: int64