In [4]:
import pandas as pd

In [5]:
delhi_df = pd.read_csv("../data/processed/cleaned_delhi_ev_data.csv")

In [6]:
print(delhi_df.shape)
print(delhi_df.columns)
delhi_df.head()

(2229, 24)
Index(['uid', 'name', 'vendor_name', 'address', 'latitude', 'longitude',
       'open', 'close', 'staff', 'postal_code', 'zone', 'available',
       'capacity', 'cost_per_unit', 'power_type', 'total', 'charger_type',
       'vehicle_type', 'supports_upi', 'supports_cash', 'supports_card',
       'supports_wallet', 'payment_methods', 'is_24x7'],
      dtype='str')

,uid,name,vendor_name,address,latitude,longitude,open,close,staff,postal_code,...,power_type,total,charger_type,vehicle_type,supports_upi,supports_cash,supports_card,supports_wallet,payment_methods,is_24x7
0,STATIC12,GensolCharge Pvt. Ltd.,GensolCharge Pvt. Ltd.,"NDSE Grid, BRPL South Extension",28.568238,77.219666,2026-07-25 00:00:00,2026-07-25 23:59:59,0,110001,...,DC,2.0,DC001,['4W'],1,0,1,1,3,1
1,STATIC14,REIL,REIL,Scada office kalka ji,28.541995,77.260583,2026-07-25 00:00:00,2026-07-25 23:59:59,0,110001,...,AC,3.0,AC001,"['2W', '3W', '4W']",0,0,0,1,1,1
2,STATIC15,REIL,REIL,Ashram Chowk Mathura Road,28.571189,77.259806,2026-07-25 00:00:00,2026-07-25 23:59:59,0,110001,...,DC,2.0,DC001,['4W'],0,0,0,1,1,1
3,STATIC16,REIL,REIL,Nizamuddin Railway station,28.588991,77.253240,2026-07-25 00:00:00,2026-07-25 23:59:59,0,110001,...,DC,4.0,DC001,['4W'],0,1,0,1,2,1
4,STATIC17,BluSmart,BluSmart,"BSES Bhawan, Nehru Place, New Delhi 110048",28.549427,77.254636,2026-07-25 00:00:00,2026-07-25 23:59:59,0,110001,...,DC,1.0,DC001,['4W'],0,1,0,1,2,1

In [7]:
fe_df = delhi_df.copy()

In [8]:
fe_df.drop(columns=["uid", "name", "address"], inplace=True)

In [10]:
fe_df[["open", "close"]].dtypes

open     str
close    str
dtype: object

In [11]:
fe_df["open"] = pd.to_datetime(fe_df["open"], format="mixed")
fe_df["close"] = pd.to_datetime(fe_df["close"], format="mixed")

In [12]:
fe_df[["open", "close"]].dtypes

open     datetime64[us]
close    datetime64[us]
dtype: object

In [13]:
fe_df["open_hour"] = fe_df["open"].dt.hour
fe_df["close_hour"] = fe_df["close"].dt.hour

In [14]:
fe_df.drop(columns=["open", "close"], inplace=True)

In [15]:
fe_df["supports_2W"] = fe_df["vehicle_type"].str.contains("2W").astype(int)
fe_df["supports_3W"] = fe_df["vehicle_type"].str.contains("3W").astype(int)
fe_df["supports_4W"] = fe_df["vehicle_type"].str.contains("4W").astype(int)

In [16]:
fe_df.head()

,vendor_name,latitude,longitude,staff,postal_code,zone,available,capacity,cost_per_unit,power_type,...,supports_cash,supports_card,supports_wallet,payment_methods,is_24x7,open_hour,close_hour,supports_2W,supports_3W,supports_4W
0,GensolCharge Pvt. Ltd.,28.568238,77.219666,0,110001,central delhi,2.0,15.0,0.0,DC,...,0,1,1,3,1,0,23,0,0,1
1,REIL,28.541995,77.260583,0,110001,central delhi,3.0,3.3,0.0,AC,...,0,0,1,1,1,0,23,1,1,1
2,REIL,28.571189,77.259806,0,110001,central delhi,2.0,15.0,0.0,DC,...,0,0,1,1,1,0,23,0,0,1
3,REIL,28.588991,77.253240,0,110001,central delhi,4.0,15.0,0.0,DC,...,1,0,1,2,1,0,23,0,0,1
4,BluSmart,28.549427,77.254636,0,110001,central delhi,1.0,15.0,0.0,DC,...,1,0,1,2,1,0,23,0,0,1

In [17]:
fe_df.drop(columns=["vehicle_type"], inplace=True)

In [18]:
fe_df.select_dtypes(include="object").nunique().sort_values()

C:\Users\mitta\AppData\Local\Temp\ipykernel_8304\1188644743.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  fe_df.select_dtypes(include="object").nunique().sort_values()

power_type       3
zone             9
charger_type    10
vendor_name     19
dtype: int64

In [19]:
fe_df = pd.get_dummies(
    fe_df,
    columns=["power_type", "zone", "charger_type", "vendor_name"],
    dtype=int
)

In [22]:
fe_df.shape
fe_df.head()
fe_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2229 entries, 0 to 2228
Data columns (total 60 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   latitude                             2229 non-null   float64
 1   longitude                            2229 non-null   float64
 2   staff                                2229 non-null   int64
 3   postal_code                          2229 non-null   int64
 4   available                            2229 non-null   float64
 5   capacity                             2229 non-null   float64
 6   cost_per_unit                        2229 non-null   float64
 7   total                                2229 non-null   float64
 8   supports_upi                         2229 non-null   int64
 9   supports_cash                        2229 non-null   int64
 10  supports_card                        2229 non-null   int64
 11  supports_wallet                      2229 non-null   int64
 12  payment_methods                      2229 non-null   int64
 13  is_24x7                              2229 non-null   int64
 14  open_hour                            2229 non-null   int32
 15  close_hour                           2229 non-null   int32
 16  supports_2W                          2229 non-null   int64
 17  supports_3W                          2229 non-null   int64
 18  supports_4W                          2229 non-null   int64
 19  power_type_AC                        2229 non-null   int64
 20  power_type_AC/DC                     2229 non-null   int64
 21  power_type_DC                        2229 non-null   int64
 22  zone_central delhi                   2229 non-null   int64
 23  zone_east delhi                      2229 non-null   int64
 24  zone_north delhi                     2229 non-null   int64
 25  zone_north east delhi                2229 non-null   int64
 26  zone_north west delhi                2229 non-null   int64
 27  zone_south delhi                     2229 non-null   int64
 28  zone_south east delhi                2229 non-null   int64
 29  zone_south west delhi                2229 non-null   int64
 30  zone_west delhi                      2229 non-null   int64
 31  charger_type_5A/15A Socket           2229 non-null   int64
 32  charger_type_AC001                   2229 non-null   int64
 33  charger_type_CCS/ CHAdeMO            2229 non-null   int64
 34  charger_type_CCS2                    2229 non-null   int64
 35  charger_type_CCS2/CHADEMO/TYPE 2 AC  2229 non-null   int64
 36  charger_type_CHAdeMO                 2229 non-null   int64
 37  charger_type_DC                      2229 non-null   int64
 38  charger_type_DC001                   2229 non-null   int64
 39  charger_type_Type 2                  2229 non-null   int64
 40  charger_type_battery_swapping        2229 non-null   int64
 41  vendor_name_BLUSMART                 2229 non-null   int64
 42  vendor_name_BSES                     2229 non-null   int64
 43  vendor_name_BluSmart                 2229 non-null   int64
 44  vendor_name_E-Fill Electric          2229 non-null   int64
 45  vendor_name_EEE                      2229 non-null   int64
 46  vendor_name_EESL                     2229 non-null   int64
 47  vendor_name_ElectriVa                2229 non-null   int64
 48  vendor_name_GensolCharge Pvt. Ltd.   2229 non-null   int64
 49  vendor_name_HPCL                     2229 non-null   int64
 50  vendor_name_JBM Renewables           2229 non-null   int64
 51  vendor_name_PlugNgo                  2229 non-null   int64
 52  vendor_name_Powerbank                2229 non-null   int64
 53  vendor_name_Pvt. Ltd.                2229 non-null   int64
 54  vendor_name_REIL                     2229 non-null   int64
 55  vendor_name_REVOS                    2229 non-null   int64
 56  vendor_name_Smart E                  2229 non-null   int64
 57  vendor_name_Sun Mobility             2229 non-null   int64
 58  vendor_name_TPDDL                    2229 non-null   int64
 59  vendor_name_Verdemobility            2229 non-null   int64
dtypes: float64(6), int32(2), int64(52)
memory usage: 1.0 MB

In [23]:
fe_df.select_dtypes(include="object").columns

Index([], dtype='str')

In [25]:
fe_df.to_csv("../data/processed/feature_engineered_ev_dataset.csv", index=False)